# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DFSampleUI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DFSampleUI

  if(ENV['TEST_BRANCH'])
    pod 'MaterialComponents', :git => 'https://github.com/material-components/material-components-ios', :branch => ENV['TEST_BRANCH']
  elsif(ENV['TEST_COMMIT'])
    pod 'MaterialComponents', :git => 'https://github.com/material-components/material-components-ios', :commit => ENV['TEST_COMMIT']
  elsif(ENV['TEST_TAG'])
    pod 'MaterialComponents', :git => 'https://github.com/material-components/material-components-ios', :tag => ENV['TEST_TAG']
  elsif(ENV['DEFAULT_BRANCH'])
    pod 'MaterialComponents', :git => 'https://github.com/material-components/material-components-ios', :branch => ENV['DEFAULT_BRANCH']
  else
    pod 'MaterialComponents', :git => 'https://github.com/material-components/material-components-ios', :branch => 'google-io-codelabs-2018'
  end

  target 'DFSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DFSampleUIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
